site_name: gtrendR
repo_url: https://github.com/tlcaputi/gtrendR/
site_author: Theodore L Caputi
site_url: https://gtrendr.readthedocs.io/
theme: readthedocs
pages:
  - About gtrendR: index.md
  - Getting Started:
    - Install the gtrendR package: installation.md
    - Pull data (R or Python): gtrendspy.md
  - Features:
    - Analyze a spike in searches: arima-one-geo.md
    - Get absolute search counts: absolute-counts.md
    - Compare spikes across several geographies: arima-multi-geo.md
    - Compare spikes across several terms: arima-multi-terms.md
  - Caveats:
    - Google Searches Vary Significantly!: google-variance.md
markdown_extensions:
    - toc:
        baselevel: 1

# pages:
#   - ['index.md', 'Homepage']
#   - ['gtrendspy.md',   'Pull data from gtrendspy']
#   - ['installation.md',   'Install the gtrendR package']
#   - ['armia-one-geo.md',   'Analyze a spike in searches']
#   - ['arima-multi-geo.md',   'Compare several geographies']
#   - ['arima-multi-terms.md',   'Compare several terms']
#   - ['absolute-counts.md',   'Retrieve absolute counts of searches from Comscore']
